### ISSUE TITLE
iPhoneOS 13 / iOS 13

### ISSUE THREAD

**Issue by brandonros** [Brandon-T/iOUSB#3]
```
[-46691881.-546876] [00000303] libusb: debug [darwin_device_from_service] set up plugin for service retry: out of resources
```

![image](https://user-images.githubusercontent.com/8949910/69069429-6f2b4b80-09f4-11ea-93ca-126b78da0358.png)

**Comment by Brandon-T** [comment]
@brandonros Are you running this on a jailbroken device? I will investigate this issue and report back.

**Comment by brandonros** [comment]
I’m not. I’m experimenting if IOKit USB support is possible on iOS/iPhoneOS without jailbreak. Do you think that’s a dumb idea?
My device is listed, I just can’t tell for sure if a user client is auto-spawend by the kernel that we can connect to.

**Comment by brandonros** [comment]
Any update? Do you specifically know what changes/gets reconfigured/gets unlocked when a phone is jailbroken versus vanilla that allows IOService connections/clients for USB?

**Comment by Brandon-T** [comment]
@brandonros I am able to use this on my iPhone on iOS 13.2.2. When NOT jailbroken, it has limited access to the USB port. When jailbroken (I used checkra1n), it has full access to the port and can read and write.

**Comment by brandonros** [comment]
> @brandonros I am able to use this on my iPhone on iOS 13.2.2. When NOT jailbroken, it has limited access to the USB port. When jailbroken (I used checkra1n), it has full access to the port and can read and write.

limited as in “able to transfer data between the phone and the device” or just read that the device is connected?

**Comment by Brandon-T** [comment]
> > @brandonros I am able to use this on my iPhone on iOS 13.2.2. When NOT jailbroken, it has limited access to the USB port. When jailbroken (I used checkra1n), it has full access to the port and can read and write.
> 
> limited as in “able to transfer data between the phone and the device” or just read that the device is connected?

When not jailbroken, I am able to read SOME things from the port.
When jailbroken and outside the sandbox, I am able to read and write to any device (Nintendo Switch included).

When jailbroken (r/w access):
![IMG_4569](https://user-images.githubusercontent.com/1530031/69396202-8053b100-0caf-11ea-9eae-bd61b840f370.PNG)

**Comment by Brandon-T** [comment]
@brandonros

When not jailbroken I get:

![image](https://user-images.githubusercontent.com/1530031/69396830-9a8e8e80-0cb1-11ea-9d8a-e3518e571805.png)

It seems to be just that the iOS app is sandboxed is all. I'm not 100% sure but I'm fairly certain it's because of sandboxing as that's currently the only difference. I wasn't able to find any entitlements that allow it normally on an iPhone but I know Apple's photos app has special entitlements that allow it to access the USB port and read/write to it.

**Comment by brandonros** [comment]
How do you sandbox / not sandbox the app? Is it sandboxed when you run it from XCode but not sandboxed when built for release?

**Comment by Brandon-T** [comment]
> How do you sandbox / not sandbox the app? Is it sandboxed when you run it from XCode but not sandboxed when built for release?

You need these entitlements: `com.apple.security.app-sandbox`

If you run it from Xcode, it is installed as a normal application. If the application is installed via a .deb or manually installed to `/Applications` on the iPhone, it will have be out of the sandbox.

The code for that is in main.mm: https://github.com/Brandon-T/iOUSB/blob/master/iOSNXLauncher/iOSNXLauncher/main.mm#L51

and the entitlements are: `com.apple.private.security.no-container`. Can also just use the one I mentioned previously.

I have also been trying to find ways to access the USB port with full access without a jailbreak. So far, no luck. I can only access it fully with a jailbreak.
I'll continue to search but it's definitely not easy lol.

I have come across a couple other entitlements such as: `com.apple.security.device.usb` but I haven't tried it yet and getting Xcode to accept it is a task in and of itself.

**Comment by brandonros** [comment]
Sorry to drag this out and thank you for being super helpful.

You are saying, as long as I do this:

![image](https://user-images.githubusercontent.com/8949910/69398472-59e64380-0cb8-11ea-87a4-054b4d2671a2.png)

I won't get `out of resources` when trying to interact with a USB device on a non-jailbroken iPhone?

**Comment by Brandon-T** [comment]
No. Whatever you do, you WILL get that error on a non-jailbroken device. I have not been able to find a way to get full access on a non-jailbroken device.

The instructions I gave is for when you are jailbroken. I have tried many times unsuccessfully to get full-access on non-jailbroken device. I will continue to look into it but I'm not sure if my peering will come up with anything clever.

**Comment by brandonros** [comment]
Ok. I'll close the issue. Thanks for your help. I wanted to make sure I was not crazy because I ran into the same problems. I thought with the iPhoneOS 13 support for USB HID devices maybe the device could be spoofed as a HID device and then `controlTransfer` / `transferIn` / `transferOut` could be called against it but I don't think that is realistic.

**Comment by brandonros** [comment]
Also, nice name.

**Comment by brandonros** [comment]
Can you think of any way to connect a USB device through RJ45 (Ethernet, which we know works with iPhones pretty well) without something like a Raspberry Pi in between?

**Comment by brandonros** [comment]
@Brandon-T 

https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_developer_driverkit_communicates-with-drivers

says it is supported iOS 16.0, does that change things here?

**Comment by Brandon-T** [comment]
> @Brandon-T 
> 
> 
> 
> https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_developer_driverkit_communicates-with-drivers
> 
> 
> 
> says it is supported iOS 16.0, does that change things here?

Hey it does, but IIRC, it is for the M1 devices only. So M1 iPad only is what they said in WWDC, but not sure now because docs look different so maybe they changed it? I'll check anyway.

https://developer.apple.com/documentation/driverkit

> The base DriverKit framework is available in macOS for Apple silicon and Intel-based Mac computers, and in iPadOS for devices with an M1 processor. The availability of family frameworks like USBDriverKit and AudioDriverKit varies by platform.

It does say the USBDriverKit varies by platform, so I can check if it works in my current iPad AND iPhone.

**Comment by brandonros** [comment]
```
case developerDriverkitFamilySerial = "com.apple.developer.driverkit.family.serial"
            case developerDriverkitTransportPci = "com.apple.developer.driverkit.transport.pci"
            case developerDriverkitTransportUsb = "com.apple.developer.driverkit.transport.usb"
```

these are kind of interesting to me

**Comment by Merati22** [comment]
Hello @brandonros and @Brandon-T 👋🏼,

I’ve recently encountered the same issue. I want to use a USB Type-C connection to communicate with my iPhone, but I’m unsure if it’s possible. Have you discovered any new information about this?
